CREATE TABLE Class_Name(
   Id_SIGNAPP_Class INT AUTO_INCREMENT,
   Name VARCHAR(300)  NOT NULL,
   Participants INT NOT NULL,
   Start_Date DATE NOT NULL,
   End_Date DATE NOT NULL,
   PRIMARY KEY(Id_SIGNAPP_Class)
);
ALTER TABLE Class_Name ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE SIGNAPP_Role(
   Id_SIGNAPP_Role INT AUTO_INCREMENT,
   Type VARCHAR(300)  NOT NULL,
   PRIMARY KEY(Id_SIGNAPP_Role)
);
ALTER TABLE SIGNAPP_Role ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE SIGNAPP_User(
   Id_SIGNAPP_User INT AUTO_INCREMENT,
   Name VARCHAR(300)  NOT NULL,
   Surname VARCHAR(300)  NOT NULL,
   Email VARCHAR(300)  NOT NULL,
   Password VARCHAR(300)  NOT NULL,
   Verified BOOLEAN NOT NULL,
   Id_SIGNAPP_Role INT NOT NULL,
   PRIMARY KEY(Id_SIGNAPP_User),
   UNIQUE(Email),
   FOREIGN KEY(Id_SIGNAPP_Role) REFERENCES SIGNAPP_Role(Id_SIGNAPP_Role)
);
ALTER TABLE SIGNAPP_User ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE SIGNAPP_Register(
   Id_SIGNAPP_Register INT AUTO_INCREMENT,
   Code INT,
   Date_Time DATETIME,
   Start_Time TIME NOT NULL,
   End_Time TIME NOT NULL,
   Id_SIGNAPP_Class INT NOT NULL,
   PRIMARY KEY(Id_SIGNAPP_Register),
   FOREIGN KEY(Id_SIGNAPP_Class) REFERENCES Class_Name(Id_SIGNAPP_Class)
);
ALTER TABLE SIGNAPP_Register ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE SIGNAPP_Status(
   Id_SIGNAPP_User INT,
   Id_SIGNAPP_Register INT,
   Name VARCHAR(300)  NOT NULL,
   _Date DATE,
   PRIMARY KEY(Id_SIGNAPP_User, Id_SIGNAPP_Register),
   FOREIGN KEY(Id_SIGNAPP_User) REFERENCES SIGNAPP_User(Id_SIGNAPP_User),
   FOREIGN KEY(Id_SIGNAPP_Register) REFERENCES SIGNAPP_Register(Id_SIGNAPP_Register)
);
ALTER TABLE SIGNAPP_Status ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE belongs_to(
   Id_SIGNAPP_User INT,
   Id_SIGNAPP_Class INT,
   PRIMARY KEY(Id_SIGNAPP_User, Id_SIGNAPP_Class),
   FOREIGN KEY(Id_SIGNAPP_User) REFERENCES SIGNAPP_User(Id_SIGNAPP_User),
   FOREIGN KEY(Id_SIGNAPP_Class) REFERENCES Class_Name(Id_SIGNAPP_Class)
);
ALTER TABLE belongs_to ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
